### ISSUE TITLE
安卓版sdk偶发性报错

### ISSUE THREAD

**Issue by Gethin0321** [snail007/goproxy-sdk#4]
@snail007 

报错时日志如下:

08-18 16:00:30.918   625     0 E Go      : panic: interface conversion: interface {} is nil, not string
08-18 16:00:30.918   625     0 E Go      : goroutine 13852 [running]:
08-18 16:00:30.918   625     0 E Go      : github.com/snail007/license/lic-checker.post(0x8bdd09a0, 0xab, 0x8be58fa0, 0xbf0e2008, 0xc8, 0x8bc994f0, 0x0, 0x0)
08-18 16:00:30.918   625     0 E Go      : 	/Users/go/src/github.com/snail007/license/lic-checker/checker.go:411 +0xd58
08-18 16:00:30.918   625     0 E Go      : github.com/snail007/license/lic-checker.Report.func1()
08-18 16:00:30.918   625     0 E Go      : 	/Users/go/src/github.com/snail007/license/lic-checker/checker.go:291 +0x3c
08-18 16:00:30.918   625     0 E Go      : created by time.goFunc
08-18 16:00:30.918   625     0 E Go      : 	/usr/local/go1.13/src/time/sleep.go:168 +0x38
08-18 16:00:30.919   625  3276 E GoLog   : panic: interface conversion: interface {} is nil, not string
08-18 16:00:30.946 23813 23821 W System  : A resource failed to call close.

**Comment by snail007** [comment]
你用了没有授权的商业版sdk。

**Comment by Gethin0321** [comment]
我用的是免费版SDK,用了很久了,今天突然报这个错的,刚刚我为了验证,重新下载了一下免费版SDK和我本地版本的对比了一下文件HASH,是一致的

**Comment by Gethin0321** [comment]
@snail007    大佬,我在github下载免费版aar的CRC32:7850FB06,项目使用的也是这个,麻烦你看下是不是BUG

**Comment by Gethin0321** [comment]
又下载商业版试了一下,商业版是直接无法启动的
